# site settings
title: Marcel Russ
subtitle: (not another programmer)
email: sag.hallo@marcelruss.de
description: A responsive site template designed by HTML5 Up<br /> and released under the Creative Commons.
baseurl: "/" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Marcel Russ
street_address: Lindachstraße 14
city: Kirchheim unter Teck
state:
zip_code: 73230
country: Deutschland
phone: +49 1573 4399963

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url:
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

sass:
  style: compressed
