# site settings
title: Marcel Russ
subtitle: (not another programmer)
email: sag.hallo@marcelruss.de
formio: https://formspree.io/f/xpzoeyqe
description: null
baseurl: "" # the subpath of your site, e.g. /blog
url: # the base hostname & protocol for your site
author: Marcel Russ

# These are only the labels, the links are set in footer.html
street_address: Lindachstraße 14 
city: Kirchheim unter Teck
state:
zip_code: 73230
country: Deutschland
phone: +49 1573 4399963 

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 6

# social settings
500px_url:
facebook_url:
github_url:
gitlab_url:
googleplus_url:
instagram_url:
linkedin_url: https://www.linkedin.com/in/marcel-russ-82a277144/
pinterest_url:
slack_url:
twitter_url:

# build settings
markdown: kramdown

# for google site verification
google_verify: 9C0Qp-Waq5Ob0Yy7Z7gZBcPrl8zK7YXyZ1m8-iXSK0w

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

sass:
  style: compressed
